### ISSUE TITLE
Auswahl der Gruppe über Link geht nicht

### ISSUE THREAD

**Issue by tokudan** [tokudan/ffhh-stats#6]
Während z.B. diese URL funktioniert wie gewünscht:
https://ff.besaid.de/dashboard/db/freifunk-knoteninfo?var-region=ffhh&var-knoten=attraktor
Klappt das bei den Gruppen zur Zeit nicht:
https://ff.besaid.de/dashboard/db/freifunk-gruppen?var-region=ffhh&var-grouptype=manual&var-group=zea-oktavio
Ist unabhängig von der Gruppe.

**Comment by ansemjo** [comment]
Habe das gerade nochmal mit diesem Link versucht:
https://statistik.hamburg.freifunk.net/dashboard/db/freifunk-gruppen?var-region=ffhh&var-grouptype=manual&var-group=zea-oktavio
.. scheint jetzt zu funktionieren.

**Comment by tokudan** [comment]
Seltsam.
Nunja, Graphite (das aktuelle Backend hinter Grafana) wird sowieso bald ersetzt, dann geht das ganze (vielleicht) von vorne los...
